---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ullswater-prereqs
  namespace: argocd
  # annotations:
  #   argocd.argoproj.io/sync-wave: "-10"
spec:
  source:
    path: apps/prereqs/
    repoURL: 'https://github.com/bolaogun/ullswater-app-of-apps'
    targetRevision: develop
    directory:
      recurse: true
  destination:
    namespace: ullswater-prereqs
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true