---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ullswater-prereqs
  namespace: argocd
  # annotations:
  #   argocd.argoproj.io/sync-wave: "-10"
spec:
  source:
    path: apps/prereqs/
    repoURL: 'https://github.com/bolaogun/ullswater-app-of-apps'
    targetRevision: develop
  destination:
    namespace: ullswater-prereqs
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true


