---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ullswater-senzing-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  source:
    path: senzing-stack
    repoURL: 'https://github.com/bolaogun/ullswater-app-of-apps'
    targetRevision: develop
    directory:
      recurse: true
  destination:
    namespace: ullswater-senzing-stack
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
